version: "3.8"
volumes:
  db-store:
services:
  app:
    build:
      context: .
      dockerfile: ./infra/docker/development/php/Dockerfile
    volumes:
      - ./laravel:/work/laravel
    networks:
      - app-network

  web:
    build:
      context: .
      dockerfile: ./infra/docker/development/nginx/Dockerfile
    ports:
      - "48080:80"
    volumes:
      - ./laravel:/work/laravel
    depends_on:
      - app
    networks:
      - app-network

  db:
    platform: linux/amd64
    build:
      context: .
      dockerfile: ./infra/docker/development/mysql/Dockerfile
    ports:
      - "43307:3306"
    volumes:
      - db-store:/var/lib/mysql
      - ./infra/docker/development/mysql/init:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=password
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
